-- ============================================================
-- 日本生命 法人営業DXデモ
-- 00_setup.sql: データベース / ウェアハウス / スキーマ / ロール作成
-- 対象アカウント: SFSEAPAC-KMOT_DEMO1
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ウェアハウス作成（既存の COCO_WORKSHOP_WH を使用可。必要に応じて専用WH作成）
CREATE WAREHOUSE IF NOT EXISTS NIPPONLIFE_DEMO_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  COMMENT = '日本生命法人営業デモ用ウェアハウス';

-- データベース作成
CREATE DATABASE IF NOT EXISTS NIPPONLIFE_DEMO_DB
  COMMENT = '日本生命 法人営業DXデモ データベース';

-- スキーマ作成
CREATE SCHEMA IF NOT EXISTS NIPPONLIFE_DEMO_DB.RAW
  COMMENT = '生データ（テーブル・マスタ）';

CREATE SCHEMA IF NOT EXISTS NIPPONLIFE_DEMO_DB.ANALYTICS
  COMMENT = '分析ビュー・Semantic View';

CREATE SCHEMA IF NOT EXISTS NIPPONLIFE_DEMO_DB.SEARCH
  COMMENT = 'Cortex Search サービス';

CREATE SCHEMA IF NOT EXISTS NIPPONLIFE_DEMO_DB.AI
  COMMENT = 'UDF・AI 関連オブジェクト';

-- デモ用ロール
CREATE ROLE IF NOT EXISTS NIPPONLIFE_DEMO_ROLE
  COMMENT = '法人営業デモ実行ロール';

GRANT USAGE ON WAREHOUSE NIPPONLIFE_DEMO_WH TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT USAGE ON DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE NIPPONLIFE_DEMO_DB TO ROLE NIPPONLIFE_DEMO_ROLE;
GRANT ROLE NIPPONLIFE_DEMO_ROLE TO ROLE ACCOUNTADMIN;

-- デフォルトコンテキスト設定
USE WAREHOUSE NIPPONLIFE_DEMO_WH;
USE DATABASE NIPPONLIFE_DEMO_DB;
USE SCHEMA RAW;

SELECT 'Setup completed successfully!' AS STATUS;
