-- ============================================================
-- 08_views.sql: 分析ビュー + V_MARKET_INSIGHT
-- ============================================================
USE DATABASE NIPPONLIFE_DEMO_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE NIPPONLIFE_DEMO_WH;

-- ────────────────────────────────────────
-- 見込み管理ダッシュボードビュー
-- ────────────────────────────────────────
CREATE OR REPLACE VIEW V_PROSPECT_DASHBOARD AS
SELECT
    p.PROSPECT_ID,
    c.COMPANY_ID,
    c.COMPANY_NAME,
    c.INDUSTRY_LARGE,
    c.EMPLOYEE_COUNT,
    c.PREFECTURE,
    c.STOCK_TICKER,
    p.PRODUCT_ID,
    ip.PRODUCT_NAME,
    p.CURRENT_RANK,
    p.PREVIOUS_RANK,
    p.PROSPECT_AMOUNT,
    p.PROBABILITY,
    p.AI_SCORE,
    p.AI_SCORE_REASON,
    p.RANKUP_ACTIONS,
    p.LAST_EVENT_TRIGGER,
    p.LAST_EVENT_DATE,
    p.EXPECTED_CLOSE_DATE,
    p.LAST_CONTACT_DATE,
    p.DAYS_SINCE_CONTACT,
    p.SALES_REP_ID,
    -- アクティブアラート数
    (SELECT COUNT(*) FROM RAW.T_EVENT_ALERTS ea
     WHERE ea.COMPANY_ID = c.COMPANY_ID AND ea.STATUS = 'UNREAD') AS UNREAD_ALERTS,
    -- 最新アラートのイベント種別
    (SELECT ea.EVENT_TYPE FROM RAW.T_EVENT_ALERTS ea
     WHERE ea.COMPANY_ID = c.COMPANY_ID AND ea.STATUS = 'UNREAD'
     ORDER BY ea.DETECTED_AT DESC LIMIT 1) AS LATEST_ALERT_TYPE,
    -- 最新アラートの優先度
    (SELECT ea.INSURANCE_RELEVANCE FROM RAW.T_EVENT_ALERTS ea
     WHERE ea.COMPANY_ID = c.COMPANY_ID AND ea.STATUS = 'UNREAD'
     ORDER BY ea.DETECTED_AT DESC LIMIT 1) AS LATEST_ALERT_RELEVANCE
FROM RAW.T_PROSPECTS p
JOIN RAW.T_CUSTOMER_COMPANIES c ON p.COMPANY_ID = c.COMPANY_ID
LEFT JOIN RAW.T_INSURANCE_PRODUCTS ip ON p.PRODUCT_ID = ip.PRODUCT_ID;

-- ────────────────────────────────────────
-- 顧客360度ビュー
-- ────────────────────────────────────────
CREATE OR REPLACE VIEW V_CUSTOMER_360 AS
SELECT
    c.*,
    -- 面談統計
    (SELECT COUNT(*) FROM RAW.T_MEETINGS m WHERE m.COMPANY_ID = c.COMPANY_ID) AS TOTAL_MEETINGS,
    (SELECT MAX(m.MEETING_DATE) FROM RAW.T_MEETINGS m WHERE m.COMPANY_ID = c.COMPANY_ID) AS LAST_MEETING_DATE,
    -- 既存契約件数
    (SELECT COUNT(*) FROM RAW.T_CONTRACTS ct WHERE ct.COMPANY_ID = c.COMPANY_ID AND ct.STATUS = 'ACTIVE') AS ACTIVE_CONTRACTS,
    -- 既存契約年間保険料合計
    (SELECT SUM(ct.ANNUAL_PREMIUM) FROM RAW.T_CONTRACTS ct WHERE ct.COMPANY_ID = c.COMPANY_ID AND ct.STATUS = 'ACTIVE') AS TOTAL_ANNUAL_PREMIUM,
    -- 未対応アラート
    (SELECT COUNT(*) FROM RAW.T_EVENT_ALERTS ea WHERE ea.COMPANY_ID = c.COMPANY_ID AND ea.STATUS = 'UNREAD') AS UNREAD_ALERT_COUNT,
    -- 見込み合計金額
    (SELECT SUM(p.PROSPECT_AMOUNT) FROM RAW.T_PROSPECTS p WHERE p.COMPANY_ID = c.COMPANY_ID) AS TOTAL_PROSPECT_AMOUNT,
    -- 最高見込みランク
    (SELECT MIN(p.CURRENT_RANK) FROM RAW.T_PROSPECTS p WHERE p.COMPANY_ID = c.COMPANY_ID) AS BEST_PROSPECT_RANK
FROM RAW.T_CUSTOMER_COMPANIES c;

-- ────────────────────────────────────────
-- アラート優先度ビュー
-- ────────────────────────────────────────
CREATE OR REPLACE VIEW V_EVENT_ALERT_PRIORITY AS
SELECT
    ea.ALERT_ID,
    ea.COMPANY_ID,
    c.COMPANY_NAME,
    c.INDUSTRY_LARGE,
    c.PREFECTURE,
    ea.EVENT_TYPE,
    ea.EVENT_SUMMARY,
    ea.INSURANCE_RELEVANCE,
    ea.ALERT_REASON,
    ea.RECOMMENDED_PRODUCTS,
    ea.RECOMMENDED_ACTION,
    ea.URGENCY_DAYS,
    ea.STATUS,
    ea.DETECTED_AT,
    ea.SALES_REP_ID,
    -- 優先度スコア（数値）
    CASE ea.INSURANCE_RELEVANCE
        WHEN '最高' THEN 100
        WHEN '高'   THEN 75
        WHEN '中'   THEN 50
        ELSE 25
    END AS PRIORITY_SCORE,
    -- 緊急度
    CASE
        WHEN ea.URGENCY_DAYS <= 3  THEN '🔴 今すぐ'
        WHEN ea.URGENCY_DAYS <= 14 THEN '🟡 今週中'
        WHEN ea.URGENCY_DAYS <= 30 THEN '🟢 今月中'
        ELSE '⚪ 通常'
    END AS URGENCY_LABEL
FROM RAW.T_EVENT_ALERTS ea
JOIN RAW.T_CUSTOMER_COMPANIES c ON ea.COMPANY_ID = c.COMPANY_ID
ORDER BY PRIORITY_SCORE DESC, ea.URGENCY_DAYS ASC;

-- ────────────────────────────────────────
-- マーケットインサイトビュー（市場データ連携用）
-- ※ 実際の市場データは財務企画部共有 MARKET_DATA_SHARED を参照
-- ※ デモ環境では固定値を使用
-- ────────────────────────────────────────
CREATE OR REPLACE VIEW V_MARKET_INSIGHT AS
SELECT
    c.COMPANY_ID,
    c.COMPANY_NAME,
    c.INDUSTRY_LARGE,
    c.PENSION_TYPE,
    c.STOCK_TICKER,
    c.EMPLOYEE_COUNT,
    -- デモ用固定市場データ（本番では MARKET_DATA_SHARED から取得）
    CASE c.COMPANY_ID
        WHEN 'C001' THEN 2850.0 WHEN 'C002' THEN  1420.0 WHEN 'C003' THEN 7280.0
        WHEN 'C004' THEN 4520.0 WHEN 'C005' THEN  680.0  WHEN 'C007' THEN 3350.0
        WHEN 'C008' THEN 4890.0 WHEN 'C009' THEN  4250.0 WHEN 'C010' THEN 4830.0
        WHEN 'C011' THEN 4120.0 WHEN 'C012' THEN  3450.0 WHEN 'C013' THEN 1820.0
        WHEN 'C014' THEN 5240.0 WHEN 'C015' THEN  2180.0 WHEN 'C016' THEN 3820.0
        WHEN 'C017' THEN 9450.0 WHEN 'C019' THEN  2640.0 WHEN 'C020' THEN 1180.0
        ELSE NULL
    END AS LATEST_STOCK_PRICE,
    CASE c.COMPANY_ID
        WHEN 'C002' THEN -4.1 WHEN 'C005' THEN -7.5 WHEN 'C006' THEN  3.2
        WHEN 'C010' THEN -2.8 WHEN 'C012' THEN  8.5 WHEN 'C016' THEN  5.8
        WHEN 'C018' THEN NULL ELSE ROUND(UNIFORM(-8, 12, RANDOM()), 1)
    END AS STOCK_1M_CHANGE_PCT,
    -- 現在の10年国債利回り（デモ固定値）
    1.45 AS CURRENT_10Y_RATE,
    0.35 AS RATE_CHANGE_1Y,
    -- DB年金への金利影響評価
    CASE
        WHEN c.PENSION_TYPE LIKE '%DB%' AND 1.45 > 1.0 THEN 'DB積立改善傾向 → DC移行の好機'
        WHEN c.PENSION_TYPE = 'DC' THEN 'DC制度のため金利影響軽微'
        ELSE 'DB積立影響確認推奨'
    END AS PENSION_RATE_SIGNAL,
    -- 見込み情報
    p.CURRENT_RANK AS PROSPECT_RANK,
    p.AI_SCORE     AS PROSPECT_AI_SCORE,
    p.PROSPECT_AMOUNT,
    -- 未対応アラート数
    (SELECT COUNT(*) FROM RAW.T_EVENT_ALERTS ea
     WHERE ea.COMPANY_ID = c.COMPANY_ID AND ea.STATUS = 'UNREAD') AS UNREAD_ALERTS
FROM RAW.T_CUSTOMER_COMPANIES c
LEFT JOIN RAW.T_PROSPECTS p
    ON p.COMPANY_ID = c.COMPANY_ID
    AND p.UPDATED_AT = (
        SELECT MAX(p2.UPDATED_AT) FROM RAW.T_PROSPECTS p2
        WHERE p2.COMPANY_ID = c.COMPANY_ID);

SELECT 'Views created: V_PROSPECT_DASHBOARD, V_CUSTOMER_360, V_EVENT_ALERT_PRIORITY, V_MARKET_INSIGHT' AS STATUS;
